### PR TITLE
update ae,vae,vaegan notebooks

### PR DESCRIPTION
**Pull request by Saran-nns**

### CODE REVIEW

**Comment by justinshenk** [comment]
Thanks for your PR! Some documentation is missing to make this useful to other researchers, namely:

- Who are these notebooks for?
- What tasks do they solve?
- How are the results of these tasks and what are the limitations?
- What is the usefulness or future directions for this research?

Please update with some documentation in the form of section headers and brief explanation. Also, since it is not possible to view the notebooks without downloading due to Github limitations, it would be great to update a README in the root with a summary of each notebook.

**Comment by Saran-nns** [comment]
Thanks for the comments. I have updated the details about the notebooks.

**Review by justinshenk — COMMENTED** [review]
I see the summary now, thank you!

**Comment by justinshenk** [comment]
@WolfByttner, does this look complete to you?

**Comment by WolfByttner** [comment]
@Saran-nns it's good to check in some examples - should we move them to a subfolder like notebooks/ ?

@justinshenk with the way PIP is configured, that doesn't get the notebooks included into the package, right?

**Comment by Saran-nns** [comment]
> @Saran-nns it's good to check in some examples - should we move them to a subfolder like notebooks/ ?
> 
> @justinshenk with the way PIP is configured, that doesn't get the notebooks included into the package, right?

@WolfByttner The notebooks are moved to a folder now. This PR is to `traja-research` repo which is independent of `traja` PyPI package.

**Comment by WolfByttner** [comment]
@Saran-nns thank you - I didn't notice! I'll approve this.

**Review by WolfByttner — APPROVED** [review]

**Comment by justinshenk** [comment]
> @Saran-nns it's good to check in some examples - should we move them to a subfolder like notebooks/ ?
> 
> @justinshenk with the way PIP is configured, that doesn't get the notebooks included into the package, right?

This research repo isn’t in PIP as far as I’m aware.

**Review by justinshenk — COMMENTED** [review]
Thanks Saran!

**Pull request merged**
